BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Users` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`BasketId`	INTEGER NOT NULL,
	`UserRankId`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `UserRanks` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Products` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Price`	INTEGER NOT NULL,
	`Amount`	INTEGER NOT NULL,
	`isAvailable`	INTEGER NOT NULL,
	`CategoryId`	INTEGER NOT NULL,
	`Rating`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Prod_Orders` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ProductId`	INTEGER NOT NULL,
	`OrderId`	INTEGER NOT NULL,
	`Amount`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Orders` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`BasketId`	INTEGER NOT NULL,
	`UserId`	INTEGER NOT NULL,
	`Date`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `OrderStatuses` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`isPaid`	INTEGER NOT NULL,
	`isOnTheWay`	INTEGER NOT NULL,
	`isDelievered`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Categories` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`isAvailable`	INTEGER NOT NULL
);
COMMIT;
