BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Users` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`BasketId`	INTEGER NOT NULL,
	`UserRankId`	INTEGER NOT NULL
);
INSERT INTO `Users` VALUES (1,'Andrzej',1,0);
INSERT INTO `Users` VALUES (2,'Stefan',2,0);
COMMIT;
